// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaotBVqGjWbmSyXQKuTu6JtRgWglGQISM',
    appId: '1:404316500121:web:ad8a82f2c03fc0f0244808',
    messagingSenderId: '404316500121',
    projectId: 'potifyclone',
    authDomain: 'potifyclone.firebaseapp.com',
    storageBucket: 'potifyclone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnDcVHuvB19216rG1MnJBdQD0eVVwCiJM',
    appId: '1:404316500121:android:e22d21d096c9f5a5244808',
    messagingSenderId: '404316500121',
    projectId: 'potifyclone',
    storageBucket: 'potifyclone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrrUhzUiT-yEYS7Zzd8i1URfpPfBZXvwU',
    appId: '1:404316500121:ios:f5c2e2d99bcdd6ed244808',
    messagingSenderId: '404316500121',
    projectId: 'potifyclone',
    storageBucket: 'potifyclone.appspot.com',
    iosBundleId: 'com.example.spotifyCloneWithFlutterUsedBlock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrrUhzUiT-yEYS7Zzd8i1URfpPfBZXvwU',
    appId: '1:404316500121:ios:f5c2e2d99bcdd6ed244808',
    messagingSenderId: '404316500121',
    projectId: 'potifyclone',
    storageBucket: 'potifyclone.appspot.com',
    iosBundleId: 'com.example.spotifyCloneWithFlutterUsedBlock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaotBVqGjWbmSyXQKuTu6JtRgWglGQISM',
    appId: '1:404316500121:web:356f0f77cd449a97244808',
    messagingSenderId: '404316500121',
    projectId: 'potifyclone',
    authDomain: 'potifyclone.firebaseapp.com',
    storageBucket: 'potifyclone.appspot.com',
  );
}
